apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  labels:
    app: weather-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app1
        image: docker.io/manukoli1986/weather-app:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: weather-app
  labels:
    app: weather-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: weather-app
  type: LoadBalancer

